var busstype = [ 
	 "Advertising",
	 "Aircon Services",
	 "Appliance Store",
	 "Appliances",
	 "Auto Electrical Supply",
	 "Auto Radiator Shop",
	 "Auto Shop",
	 "Auto Supply",
	 "Bookstore",
	 "Car Accessories",
	 "Car Battery Supply",
	 "Computer Parts",
	 "Computer Supplies",
	 "Electronics",
	 "Forms and Paper Products",
	 "Hardware",
	 "Ink Supply",
	 "Marketing",
	 "Office and Computer Supplies",
	 "Office Supplies",
	 "Pharmacy",
	 "Printing Press",
	 "Publishing House",
	 "Sales & Marketing",
	 "Signage",
	 "Super Market",
	 "Supermarket",
	 "Tire Supply",
	 "Travel Agency",
 ];
